### ISSUE TITLE
Support for Audi B8 platform

### ISSUE THREAD

**Issue by brmccrary** [jyoung8607/openpilot#105]
I saw a message about B8 testing on AudiWorld but thought I might open an issue here, so please close if this should be elsewhere.

I have an 08 Audi S5 w/ACC and would like to try to get openpilot working.  I think the main issue is the steering, as the B8 platform only had lane assist, instead of active lane assist.  Since the steering wheel itself can't move, a new EPS rack would need to be installed, but this looks to be possible.  I guess the main thing is how much does openpilot handle and if the factory active lane assist is involved in making openpilot work.  Since there would be no assistance from the car's systems, it would essentially be up to openpilot to send the commands directly to the EPS to steer.  If this is something that might be a possibility, I'm willing to give it a try!

**Comment by jyoung8607** [comment]
Welcome! Yes, we can help you get this working. Just a matter of tweaking the Lane Assist enabled bit in address 44 and we can take care of steering, it's far more important to have ACC and you have that.

Quickest way to get started is to join the support Discord at https://discord.comma.ai. If you jump into #volkswagen-audi-skoda and say hello, I can get you into the thread where I'm already working with a couple other MLB owners.
