### ISSUE TITLE
Need better gearshift handling for e-Golf

### ISSUE THREAD

**Issue by jyoung8607** [jyoung8607/openpilot#34]
We're missing Getriebe_11 because there is no traditional gearbox. We can find a reverse signal easily, but neutral/park/drive confirmation are difficult at this time.

e-Golf specific messages we may want to look at: 0x187, 0x59E, 0x5B5.

**Comment by jyoung8607** [comment]
0x187 byte 2 bits 0-3 look very good for a gearshift signal.

* 2 = park
* 3 = reverse
* 5 = neutral
* 6 = drive

Unknown if drive regen modes show up in here, it's fine if they don't.

**Comment by jyoung8607** [comment]
Confirmed 0x187 mappings with @Alwik:

Byte 2 bits 0-3 are selected gear:
- 2 = park
- 3 = reverse
- 4 = neutral
- 5 = drive
- 6 = b-mode (most aggressive regen braking)

Byte 1 bits 4-5 are regen level in drive:
- 0 = default
- 1 = B2
- 2 = B2
- 3 = B3

The usage paradigm for these on e-Golf is really weird. The B-mode "gear" is really more like Drive with B4 regen (one step beyond B3). I think I will probably map all Drive modes to Drive and B-mode to Eco. It's either that or call them all Drive, which might be just as correct.

I will need to upstream a DBC update, and break the CRC padding bytes before integration.

**Comment by Alwik** [comment]
I would suggest using your second option, just call all of them Drive. Eco is really something different!
And you have a type: 1 = B1

**Comment by jyoung8607** [comment]
Consider it done. I'll certainly take the opinion of an e-Golf owner/operator above my own. :)

**Comment by jyoung8607** [comment]
The OpenDBC portion has been merged: commaai/opendbc#193.

**Comment by jyoung8607** [comment]
Auto-detect of EV_Gearshift vs Getriebe_11 is tested and working well as of VW community port commits b99abac2e021697f820a176769b73a17d8a75c45 and 5bfe54951453520aac8761b707087a65267fec79, available in VW community 0.7.4-VW1.3.
