### ISSUE TITLE
PQ steering timeout after 6 minutes

### ISSUE THREAD

**Issue by jyoung8607** [jyoung8607/openpilot#41]
I'm reliably informed that PQ steering racks are only willing to steer for 6 minutes, then fault out. The exact recovery steps aren't known yet, but it's a non-permanent fault. It seems we can get control back after a couple seconds of the driver Doing Something.

Waiting for data to look at this offline now that we've fixed some other bugs. We have a couple things we can try to force a reset, much like we do for MQB today (it has the same timer). If all else fails, we can force an OP DM steering wheel touch every 5 minutes.

**Comment by CineXWorm** [comment]
Timebomb can be bypassed in 1.05 seconds reliably.

**Comment by jyoung8607** [comment]
Rendered moot by Willem's awesome work: https://blog.willemmelching.nl/carhacking/2022/01/02/vw-part1/
