### ISSUE TITLE
Should provide haptic feedback during OP lane departure events

### ISSUE THREAD

**Issue by jyoung8607** [jyoung8607/openpilot#44]
We have control of this in HCA_01/HCA_1, just haven't used it yet. Would be nice to provide this as additional feedback, esp. in combination with the new "unsafe mode" weak steering to provide an OEM-like lane guidance while disengaged.

**Comment by nabeelr** [comment]
Yeah, for what it's worth, this would be awesome! The gentile nudge when you start to stray on long drives is handy.

**Comment by jyoung8607** [comment]
I may do this at some point, it won't be hard, but it would diverge from the typical openpilot experience for other cars, and as such, probably wouldn't be upstreamed. The stock openpilot experience is my primary focus right now.
