### ISSUE TITLE
Re-engagement of OP immediately after disengagement, sometimes only actvates stock ACC

### ISSUE THREAD

**Issue by nabeelr** [jyoung8607/openpilot#46]
**Describe the bug**
After pressing the gas pedal to merge into traffic and hitting the resume button again to get OP to take over, VWs stock ACC system engaged, however OP was still disengaged.

**How to reproduce or log data**
I can share the data privately, please PM me Semi-Lucent on Comma.ai Discord.
It seems that comma explorer doesn't show the disengagement in the timeline, however it did indeed disengage with the gas pedal. I tried to re-engage afterwards and the stock ACC system engaged instead of OP, I had to cancel ACC and then resume again for OP to work again. This can be seen as the small brake in engagement on the timeline after 22:38:00, or 1000 on cabana on date Tue, 13 Oct, 2020.

**Expected behavior**
OP to have fully disengaged, and been aware that it disengaged, then re-engaged fully afterwards when the resume button was pressed.

**Device/Version information (please complete the following information):**
 - Device: Comma 2
 - Version:   openpilot v0.7.9-VW-release release2
 - Car make/model: 2019 Volkswagen Golf R

**Additional context**
Afterwards, I noticed that the "Max speed" display wasn't showing what the ACC was set to, while OP was working. I had to reboot my C2 to get that readout to work again, though the rest of OP seemed to be working. Not sure if this issue is related at all or not. I noticed afterwards, but it very well could have been happening before and gone un-noticed by me and be totally unrelated to the above.

**Comment by jyoung8607** [comment]
Sorry I haven't looked at Issues in awhile. This concern is very old, and probably not applicable to the version of openpilot you're running now. We've spoken on Discord recently, just let me know if this is still a repeatable concern.

**Comment by nabeelr** [comment]
Yeah, this weirdness has been gone for a while. I probably should have circled back too. Thanks as always James! :)
