### ISSUE TITLE
OP intermitantly loses "max speed" readout on C2 display, dispite OP being active, and ACC having speed set.

### ISSUE THREAD

**Issue by nabeelr** [jyoung8607/openpilot#47]
**Describe the bug**
OP lost the "Max Speed" readout on the C2 and was just showing up blank as it does after first booting. Changing speed on ACC or toggling ACC on and off didn't fix the issue. The C2 needed to be rebooted.

**How to reproduce or log data**
Unknown. It's possibly associated to #46 but also possibly not.

**Expected behavior**
OP should be reflecting what the set ACC speed is on the C2 display.

**Device/Version information (please complete the following information):**
 - Device: Comma 2
 - Version:  openpilot v0.7.9-VW-release release2
 - Car make/model 2019 VW Golf R

**Additional context**

**Comment by jyoung8607** [comment]
Same as your other recent issue, let me know if you run into this with a more modern version of openpilot.

**Comment by nabeelr** [comment]
Haven't seen that issue in MONTHS. So, It's good, I'd say. ;) Thanks James!
