### ISSUE TITLE
Add Q2 fingerprint

### ISSUE THREAD

**Issue by pimboli** [jyoung8607/openpilot#48]
Hello @jyoung8607 ,

can you please add the Q2 fingerprint to the values.py?

1982: 8, 506: 8

Thank you

**Comment by jyoung8607** [comment]
I think you also had a PR for this. Would love to get you supported on a more modern version of openpilot, but for that we'll need to get some different data. Reach out on comma's Discord in #volkswagen-audi and we'll get you set up. Thanks!
