### ISSUE TITLE
Update file bolt not found when we switch branch from commai to vw.

### ISSUE THREAD

**Issue by wlrnet** [jyoung8607/openpilot#51]
Hi all,
I found there has a issue that device can't get update files, it's show "failed to download recovery" when I switch branch from comma.ai to this repo branch..

I found in release 2 branch, this file "openpilot/installer/updater/update.json" has some file can't access...

ota_url": "https://commadist.azureedge.net/neosupdate/ota-signed-efdf7de63b1aef63d68301e6175930991bf9a5927d16ec6fcc69287e2ee7ca4a.zip",

  "recovery_url": "https://commadist.azureedge.net/neosupdate/recovery-97c27e6ed04ed6bb0608b845a2d4100912093f9380c3f2ba6b56bccd608e5f6e.img",

has any friends resolved now?
Thanks.

**Comment by wlrnet** [comment]
Or is there any way to block this automatic upgrade?

**Comment by DEEgao888** [comment]
Same problem here, just got my Comma two device, after SHH it shows update needed and then "failed to download recovery." From some else recommendation, might need to downgrade to NEOS 14? Got this solved yet?

**Comment by jyoung8607** [comment]
The old copy of NEOS 14 has been cached in a location where my old 0.7.9 branch can still get it, so new installs of that branch should be smooth and easy again. That said, that branch only still exists for the convenience of folks with outdated unsupported hardware that haven't upgraded yet, and won't get any further updates. Now that VW support has gone fully upstream, anybody with a LeEco EON and Black Panda, or a Comma Two, should upgrade to stock openpilot for a vastly improved experience.
